<?php

/**
 * @file
 * Contains brandfolder.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Brandfolder\Brandfolder;

/**
 * Brandfolder helper function.
 *
 * Helper function to get a Brandfolder object that can be used to interact with
 * the Brandfolder API.
 *
 * @param string|null $api_key
 *   If provided, an API key to use when connecting to Brandfolder. If not
 *   provided, the default API key set in the module configuration will be used.
 *
 * @return bool|object
 *   A \Brandfolder\Brandfolder object for interacting with the Brandfolder SDK,
 *   or FALSE on failure.
 */
function brandfolder_api(string $api_key = NULL) {
  // Get the default API key from module configuration if none is explicitly
  // provided.
  if (is_null($api_key)) {
    $api_key = \Drupal::config('brandfolder.settings')->get('api_key');
  }
  if (empty($api_key)) {
    return FALSE;
  }

  // @todo: Set Brandfolder and collection based on module config if present.

  // Return a new Brandfolder object.
  return new Brandfolder($api_key);
}

/**
 * Implements hook_help().
 */
function brandfolder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the Brandfolder module.
    case 'help.page.brandfolder':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows Drupal developers to easily integrate with a Brandfolder account.') . '</p>';

      return $output;
  }
}
