brandfolder.settings:
  type: config_object
  label: 'Brandfolder Settings'
  mapping:
    api_key:
      type: string
      label: 'Default API key for interacting with Brandfolder REST API'
    default_brandfolder:
      type: string
      label: 'ID of a Brandfolder to use for all operations by default'
    default_collection:
      type: string
      label: 'ID of a Collection to use for all operations by default'
