brandfolder.settings:
  type: config_object
  label: 'Brandfolder Settings'
  mapping:
    api_key_ids.admin:
      type: string
      label: 'The name/ID of a key in the key repository (where that key is a Brandfolder API key for an Admin user)'
    api_key_ids.collaborator:
      type: string
      label: 'The name/ID of a key in the key repository (where that key is a Brandfolder API key for a Collaborator user)'
    api_key_ids.guest:
      type: string
      label: 'The name/ID of a key in the key repository (where that key is a Brandfolder API key for a Guest user)'
    brandfolder_id:
      type: string
      label: 'ID of the Brandfolder to be integrated with the Drupal site'
    preview_collection_id:
      type: string
      label: 'ID of a Collection to use for previewing assets to test basic integration functionality'
    metadata_sync_mode:
      type: string
      label: 'How to handle the relationship between Brandfolder metadata and Drupal metadata'
    alt_text_custom_field:
      type: string
      label: 'The ID of a Brandfolder custom field used to store alt-text for images'
    customize_entity_browser_modal_pages:
      type: boolean
      label: 'Whether to customize the page structure within which Brandfolder Browser Entity Browsers are rendered'
    disable_system_messages_on_browser_pages:
      type: boolean
      label: 'Whether to disable Drupal system messages on Brandfolder browser pages'
    verbose_log_mode:
      type: boolean
      label: 'Whether to log things like Brandfolder API calls, etc.'
    io_format_auto:
      type: boolean
      label: 'Whether to use the "format=auto" option when delivering CDN images.'
    io_format_auto_force:
      type: boolean
      label: 'Whether to always use the "format=auto" option when delivering CDN images, even if another format is set for a particular image context/request.'
    io_auto_webp:
      type: boolean
      label: 'Whether to serve all applicable CDN images using the WebP format when WebP support is detected'
    io_quality:
      type: integer
      label: 'The quality level to use for all compressed images (1-100)'
